### ISSUE TITLE
Flash messages persist in their view prior to re-rendering

### ISSUE THREAD

**Issue by katstasaph** [katstasaph/tsj#6]
How to reproduce: Perform an action that results in a flash message being shown. Navigate away from that page and back to it.

What should happen: The flash message no longer appears on the page.

What actually happens: The flash message appears briefly before disappearing, causing the page to "flicker" noticeably.

Almost certainly caused by failing to tell Turbo not to cache the flash messages

**Comment by katstevens** [comment]
Having a look at this one - I'm not familiar with Turbo (aside from what I've just read in the docs!) and can't recreate locally, but I'll stick some cache=false attributes into the flash elements in application.html.erb (`<p class="notice">` and `<p class="alert">`) and see what happens.
